List<String> touristPlacesInKozhikode = [
  "Kozhikode Beach",
  "Kappad Beach",
  "Sultan's Battery",
  "Tali Temple",
  "Mananchira Square",
  "Pazhassi Raja Museum",
  "Lokanarkavu Temple",
  "Kozhikode Corporation Park",
  "Wayanad Wildlife Sanctuary",
  "Kirtads Museum",
  "Thusharagiri Waterfalls",
  "Vadakara",
  "Pazhassi Raja's Tomb",
  "Peruvannamuzhi Dam",
  "Calicut Lighthouse",
  "Beypore Beach",
  "Hilltop Park",
  "Irinjalakuda Church",
  "Vellari Mala",
  "Ramakrishna Ashram",
  "Sarovaram Bio Park",
  "SM Street (Sweet Meat Street)",
  "Conolly Canal",
  "Lion's Park",
  "Kadalundi Bird Sanctuary",
  "Elathur"
];
